import js from "@eslint/js";
import tsParser from "@typescript-eslint/parser";
import tsPlugin from "@typescript-eslint/eslint-plugin";
import reactHooks from "eslint-plugin-react-hooks";

const IGNORED_PATTERNS = [
  "build/**",
  "dist/**",
  "node_modules/**",
  "backend/**",
  ".rag/**",
  ".appwrite-deploy/**",
  ".deploy-staging/**",
  "starter-for-react/**",
  "functions/**/index.js",
  "functions/meta.json",
  "functions/package-lock.json",
  "src/BEATS_INTEGRATION_SNIPPET.tsx",
  "src/COPY_PASTE_READY_STRUCTURE_BEATS.tsx",
  "src/PASTE_THIS_INTO_PROJECTSPAGE.tsx",
  "src/STRUCTURE_BEATS_SNIPPET.tsx",
  "src/components/BookDropdown.OPTIMIZED_EXAMPLE.tsx",
  "src/components/FilmDropdown.OPTIMIZED_EXAMPLE.tsx",
  "src/components/NativeBookView-temp.tsx",
  "src/components/VideoEditorTimeline_CLEAN.tsx",
  "src/lib/test-imports.ts",
];

export default [
  {
    ignores: IGNORED_PATTERNS,
  },
  js.configs.recommended,
  {
    files: ["src/**/*.{ts,tsx}"],
    languageOptions: {
      parser: tsParser,
      parserOptions: {
        project: "./tsconfig.json",
        ecmaVersion: "latest",
        sourceType: "module",
      },
      globals: {
        console: "readonly",
        process: "readonly",
        Buffer: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        fetch: "readonly",
        URL: "readonly",
        URLSearchParams: "readonly",
        window: "readonly",
        document: "readonly",
        navigator: "readonly",
        localStorage: "readonly",
        indexedDB: "readonly",
        confirm: "readonly",
        Audio: "readonly",
        Image: "readonly",
        HTMLElement: "readonly",
        Event: "readonly",
        CustomEvent: "readonly",
        FileReader: "readonly",
        Blob: "readonly",
        File: "readonly",
        self: "readonly",
        postMessage: "readonly",
        requestAnimationFrame: "readonly",
        cancelAnimationFrame: "readonly",
        queueMicrotask: "readonly",
        TextEncoder: "readonly",
        TextDecoder: "readonly",
        ReadableStream: "readonly",
        WritableStream: "readonly",
        TransformStream: "readonly",
      },
    },
    plugins: {
      "@typescript-eslint": tsPlugin,
      "react-hooks": reactHooks,
    },
    rules: {
      ...tsPlugin.configs.recommended.rules,
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/no-unused-vars": "off",
      "no-console": "off",
      "no-undef": "off",
      "react-hooks/rules-of-hooks": "error",
      "react-hooks/exhaustive-deps": "off",
    },
  },
  {
    files: ["functions/**/*.ts", "local-bridge/**/*.ts"],
    languageOptions: {
      parser: tsParser,
      parserOptions: {
        ecmaVersion: "latest",
        sourceType: "module",
      },
      globals: {
        console: "readonly",
        process: "readonly",
        Buffer: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        fetch: "readonly",
        URL: "readonly",
        URLSearchParams: "readonly",
        queueMicrotask: "readonly",
        TextEncoder: "readonly",
        TextDecoder: "readonly",
        ReadableStream: "readonly",
        WritableStream: "readonly",
        TransformStream: "readonly",
      },
    },
    plugins: {
      "@typescript-eslint": tsPlugin,
    },
    rules: {
      ...tsPlugin.configs.recommended.rules,
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/no-unused-vars": "off",
      "no-console": "off",
      "no-undef": "off",
      "no-useless-assignment": "off",
    },
  },
];
